### ISSUE TITLE
TODO: replace ALL default exports with named

### ISSUE THREAD

**Issue by edez1t** [MikhailovIgor/tradingMetals#10]
replace default exports with named!

**Comment by MikhailovIgor** [comment]
Let’s work in that direction: if you’re offering to replace one with another, I’d like the crew to know why you’re offering it, the benefits of your decision, some explanations. In my humble opinion In this particular case, it’s a matter of style. And there’s no advantage. I think the answer is no.

**Comment by edez1t** [comment]
easier to navigate when project gets bigger
